### ISSUE TITLE
Most macros dont work at all.

### ISSUE THREAD

**Issue by Lifthraser** [brunocalado/dungeon-world-macros#2]
Those macros do nothing:
- Coin manager
- EXP manager
- Instant NPC
- Open GM screen
- Set token bar

The HP manager send buggy messages in the chat

Treasure macro seems to work.

**Comment by brunocalado** [comment]
> Those macros do nothing:
> 
> * Coin manager
> * EXP manager
> * Instant NPC
> * Open GM screen
> * Set token bar
> 
> The HP manager send buggy messages in the chat
> 
> Treasure macro seems to work.

I don't update this module anymore.

This is the only one I'll update.
https://github.com/brunocalado/dungeon-world-extra-content
